---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: react-flask-app
  name: react-flask-app
  labels:
    app: react-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-flask-app
  template:
    metadata:
      labels:
        app: react-flask-app
    spec:
      containers:
        - name: flask-backend
          image: nomanakram29/reactjs-flask-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
            - name: JWT_SECRET_KEY
              value: super-secret
            - name: SECRET_KEY
              value: super-secret
          imagePullPolicy: Always
        - name: react-frontend
          image: nomanakram29/reactjs-flask-frontend:latest
          ports:
            - containerPort: 5173
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: react-flask-app
  name: flask-backend-service
  labels:
    app: react-flask-app
spec:
  type: ClusterIP
  selector:
    app: react-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  namespace: react-flask-app
  name: react-frontend-service
  labels:
    app: react-flask-app
spec:
  type: LoadBalancer
  selector:
    app: react-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
